import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <title>Pastel Daydream Party!</title>
                <meta
                    name="description"
                    content="I'm throwing a pastel daydream-themed party! Please RSVP here and read through the details :D"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body
                className="antialiased h-full w-full"
            >
                {children}
            </body>
        </html>
    );
}
